import type { Product, Category } from "./types"

export const categories: Category[] = [
  { id: "1", name: "Phones", icon: "smartphone" },
  { id: "2", name: "Computers", icon: "monitor" },
  { id: "3", name: "SmartWatch", icon: "watch" },
  { id: "4", name: "Camera", icon: "camera" },
  { id: "5", name: "HeadPhones", icon: "headphones" },
  { id: "6", name: "Gaming", icon: "gamepad" },
]

export const flashSaleProducts: Product[] = [
  {
    id: "1",
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 5,
    reviews: 88,
    image: "/HAVIT HV-G92 Gamepad.png",
    category: "Gaming",
    colors: ["#000000", "#DB4444"],
    inStock: true,
  },
  {
    id: "2",
    name: "AK-900 Wired Keyboard",
    price: 960,
    originalPrice: 1160,
    discount: 35,
    rating: 4,
    reviews: 75,
    image: "/AK-900 Wired Keyboard.png",
    category: "Gaming",
    colors: ["#000000"],
    inStock: true,
  },
  {
    id: "3",
    name: "IPS LCD Gaming Monitor",
    price: 370,
    originalPrice: 400,
    discount: 30,
    rating: 5,
    reviews: 99,
    image: "/IPS LCD Gaming Monitor.png",
    category: "Computers",
    colors: ["#000000"],
    inStock: true,
  },
  {
    id: "4",
    name: "S-Series Comfort Chair",
    price: 375,
    originalPrice: 400,
    discount: 25,
    rating: 4.5,
    reviews: 99,
    image: "/S-Series Comfort Chair.png",
    category: "Gaming",
    colors: ["#DB4444", "#000000"],
    inStock: true,
  },
  {
    id: "5",
    name: "S-Series Comfort Chair",
    price: 160,
    originalPrice: 170,
    discount: 20,
    rating: 4.5,
    reviews: 65,
    image: "/S-Series Comfort Chair.png",
    category: "Computers",
    colors: ["#000000"],
    inStock: true,
  },
]

export const bestSellingProducts: Product[] = [
  {
    id: "6",
    name: "The North Coat",
    price: 260,
    originalPrice: 360,
    rating: 5,
    reviews: 65,
    image: "/The North Coat.png",
    category: "Fashion",
    colors: ["#F5F5DC", "#000000"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "7",
    name: "Gucci Duffle Bag",
    price: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviews: 65,
    image: "/Gucci Duffle Bag.png",
    category: "Fashion",
    colors: ["#8B4513"],
    inStock: true,
  },
    {
    id: "8",
    name: "RGB liquid CPU cooler",
    price: 160,
    rating: 4.5,
    reviews: 65,
    image: "/RGB liquid CPU cooler.png",
    category: "Gaming",
    colors: ["#000000", "#DB4444"],
    inStock: true,
  },
  {
    id: "9",
    name: "Small BookSelf",
    price: 360,
    rating: 5,
    reviews: 65,
    image: "/Small BookSelf.png",
    category: "Home",
    colors: ["#DEB887"],
    inStock: true,
  },
]

export const exploreProducts: Product[] = [
  {
    id: "10",
    name: "Breed Dry Dog Food",
    price: 100,
    rating: 3,
    reviews: 35,
    image: "/Breed dry dog food.png",
    category: "Pets",
    inStock: true,
  },
  {
    id: "11",
    name: "CANON EOS DSLR Camera",
    price: 360,
    rating: 4,
    reviews: 95,
    image: "/CANON EOS DSLR Camera.png",
    category: "Camera",
    colors: ["#000000"],
    inStock: true,
  },
  {
    id: "12",
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    rating: 5,
    reviews: 325,
    image: "/ASUS FHD Gaming Laptop.png",
    category: "Computers",
    colors: ["#000000"],
    inStock: true,
  },
  {
    id: "13",
    name: "Curology Product Set",
    price: 500,
    rating: 4,
    reviews: 145,
    image: "/Curology Product Set.png",
    category: "Beauty",
    inStock: true,
  },
  {
    id: "14",
    name: "Kids Electric Car",
    price: 960,
    isNew: true,
    rating: 5,
    reviews: 65,
    image: "/kids-electric-car.png",
    category: "Toys",
    colors: ["#DB4444", "#000000"],
    inStock: true,
  },
  {
    id: "15",
    name: "Jr. Zoom Soccer Cleats",
    price: 1160,
    rating: 5,
    reviews: 35,
    image: "/jr. zoom soccer cleats.png",
    category: "Sports",
    colors: ["#FFD700", "#000000"],
    sizes: ["38", "39", "40", "41", "42"],
    inStock: true,
  },
  {
    id: "16",
    name: "Quilted Satin Jacket",
    price: 660,
    rating: 4.5,
    reviews: 55,
    image: "/Frame 608.png?height=180&width=180",
    category: "Fashion",
    colors: ["#228B22", "#000000"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
  },
  {
    id: "17",
    name: "GP11 shooter USB Gamepad",
    price: 660,
    isNew: true,
    rating: 4.5,
    reviews: 55,
    image: "/Gamepad.png?height=180&width=180",
    category: "Gaming",
    colors: ["#000000"],
    inStock: true,
  },
]

export const allProducts: Product[] = [...flashSaleProducts, ...bestSellingProducts, ...exploreProducts]

export const getProductById = (id: string): Product | undefined => {
  return allProducts.find((product) => product.id === id)
}

export const getProductsByCategory = (category: string): Product[] => {
  return allProducts.filter((product) => product.category.toLowerCase() === category.toLowerCase())
}

export const getRelatedProducts = (productId: string, category: string): Product[] => {
  return allProducts.filter((product) => product.category === category && product.id !== productId).slice(0, 4)
}
